### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [bpeel/prevo#1]
Bonvolu aldonu al F-Droid. La fadeno por ĝia inkluzo estas ĉi tie: https://f-droid.org/forums/topic/prevo/

**Comment by bpeel** [comment]
Dankon pro la sugesto. Ankaŭ mi multe ŝatus ke tio okazu, sed mi ne scias se mi rajtas mem aldoni ĝin, ĉu? Mi ja kontribuas al tiu fadeno por provi helpi la aliajn. Mi pensas ke la problemo kiun ili havis antaŭe ne plu okazos.

**Comment by pizzamaker** [comment]
@bpeel Vi povas kontribui iel por rapidigi la procedon: https://f-droid.org/contribute/

**Comment by pizzamaker** [comment]
Jen la manlibro por aldoni la metadatumojn: https://f-droid.org/manual/

**Comment by bpeel** [comment]
Ĝi finfine aperis en la katalogo: https://f-droid.org/repository/browse/?fdid=uk.co.busydoingnothing.prevo
