### ISSUE TITLE
Add Science Vocabulary

### ISSUE THREAD

**Issue by Pantyhose-X** [bpeel/prevo#12]
[The Metathesaurus forms the base of the UMLS and comprises over 1 million biomedical concepts and 5 million concept names
There are 5 million words in medicine](https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html
),
Vocabulary [arXiv dataset and metadata of 1.7M+ scholarly papers across STEM ](https://www.kaggle.com/datasets/Cornell-University/arxiv) and it's impossible to create them one by one manually, so I feel like need to write a python program to create these words,
Then use [Apertium](https://github.com/apertium) and [gpt-neox](https://github.com/EleutherAI/gpt-neox) to make them translate to other languages,
Building [TTS](https://github.com/coqui-ai/TTS) 

---
Please create a group at https://rvlt.gg/ and let's discuss some questions

**Comment by bpeel** [comment]
Hi. I’m not sure if I understand what you are proposing correctly. Is the idea to add these scientific terms to PReVo? Please note that PReVo is just an android app for the data contained in the Reta Vortaro. If you want to add words to that dictionary, you can find their contact details on the [website](https://reta-vortaro.de/). However, I have a feeling that they will say that adding 5 million domain-specific words wouldn’t be appropriate for a general purpose dictionary and instead they would be better kept apart in a specialised dictionary.
