### ISSUE TITLE
text a bit outside the screen

### ISSUE THREAD

**Issue by castilma** [bpeel/prevo#4]
i'm on android 7.1.2, on a galaxy s4.
the text is a bit outside the left screen border.
![pic](https://user-images.githubusercontent.com/17392981/35477784-bfc05f6c-03cb-11e8-8e31-bf3b21250fe5.jpg)

however, when i make a screenshot. it looks okay.
![screenshot_20180128-002747](https://user-images.githubusercontent.com/17392981/35477718-14e7c61c-03ca-11e8-9fbb-5ca4e166347c.png)

I don't have that problem with any other app. I think the problem here is that the text starts at the very edge of the screen. Could you make the text start a few pixel further away from the edges?

Thank you for this App!

**Comment by bpeel** [comment]
Thanks for the bug report. I’ve added a bit of padding to the edges in version 0.16. Hopefully that should fix the problem for you.
